// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AKindOfBlue
{
    internal sealed partial class Vsix
    {
        public const string Id = "AKindOfBlue.3a323a8c-789f-442b-a07a-c240a819753e";
        public const string Name = "Blue Steel Theme";
        public const string Description = @"Improvised version of the the original Blue theme found in Visual Studio 2022. Requires Visual Studio 2022+";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "poppastring";
        public const string Tags = "theme";
        public const bool IsPreview = false;
    }
}
